### PR TITLE
[*] Changes registry in package-lock to default

### PR DESCRIPTION
**Pull request by Matt-Beldon-CDS**
[*] Adds npmrc files to enforce default registry

### CODE REVIEW

**Comment by andy-smith-cds** [comment]
the npm i is failing - "no such directory" for the node modules

**Comment by Matt-Beldon-CDS** [comment]
> the npm i is failing - "no such directory" for the node modules

will look into it, not sure what could be causing that 🤔

**Comment by Matt-Beldon-CDS** [comment]
@ReallySmall not sure what to do with this one, works fine for me and can't replicate Andy's issues

**Comment by andy-smith-cds** [comment]
> 

Let me delete node modules/package-lock and try again. Probably something to do with my local as it was me causing the nexus issue

**Comment by andy-smith-cds** [comment]
> > 
> 
> Let me delete node modules/package-lock and try again. Probably something to do with my local as it was me causing the nexus issue

ok @Matt-Beldon-CDS it took half an hour to re-install all the modules but it worked fine haha. That's my bad for not googling the error

**Pull request closed without merging**
