### PR TITLE
Add comment button at top of page to let you scroll into form comment box

### PR DESCRIPTION
**Pull request by jpmaHub**
Created new branch from recent main branch

- added scroll into comment box 
- Decided not to add focus on the comment textbox area because the current text box library is not NextJS compatible and raise accessibility issues. The code we implemented does focus on the box for us, but if the page renders slowly, it will take you to the bottom but won't always auto focus.

new-gif

### CODE REVIEW

**Comment by simplybenuk** [comment]
@rio-k9 @jpmaHub the "current text box library" is this something to something compatible?

**Comment by jpmaHub** [comment]
@simplybenuk It is not compatible.

**Comment by simplybenuk** [comment]
@jpmaHub sorry I didn't write that very well. I meant is this something we can change to something that is compatible?

**Review by tim-hunt — APPROVED** [review]

**Comment by rio-k9** [comment]
@simplybenuk I can certainly have a look to see what there is for Next compatibility and report back

**Pull request merged**
