### PR TITLE
TRY-JW-GroupSite-CreatedBy-Dynamic

### PR DESCRIPTION
**Pull request by JackWCDS**
[*] SeedData now gets GroupSite table CreatedBy field values dynamically from Group
[*] GroupSite CreatedBy field is now nullable to reflect Group CreatedBy field

### CODE REVIEW

**Comment by Alex-Grubba-CDS** [comment]
@JackWCDS I've already got a change in for Automation Seed along with bunch of other changes. You okay to revert yours?

**Comment by JackWCDS** [comment]
@Alex-Grubba-CDS no problem man 👍

**Review by Matt-Beldon-CDS — APPROVED** [review]
Should created by be nullable?

**Comment by JackWCDS** [comment]
@Matt-Beldon-CDS it gets populated with group table createdby field which is also nullable and doesn't have seed values

**Pull request merged**
