### PR TITLE
TRY-JW-89853-Admin-Manage-Members

### PR DESCRIPTION
**Pull request by Matt-Beldon-CDS**
[+] update user/member endpoint

body expects:
- firstName
- lastname
- id (userId)
- pronouns
- an image

### CODE REVIEW

**Review by Tim-Hunt-CDS — COMMENTED** [review]
Does this feature not include the ability to alter a user’s role?

**Comment by Matt-Beldon-CDS** [comment]
> Does this feature not include the ability to alter a user’s role?

Though that would be part of it yeah but that's not part of the AC, 

```
When I select edit user 
Then I will be redirected the users member profile in edit mode 
```

so it'll be the same options as a user editing their profile just admins can do it.

**Comment by Tim-Hunt-CDS** [comment]
> > Does this feature not include the ability to alter a user’s role?
> 
> Though that would be part of it yeah but that's not part of the AC,
> 
> ```
> When I select edit user 
> Then I will be redirected the users member profile in edit mode 
> ```
> 
> so it'll be the same options as a user editing their profile just admins can do it.

Ok, create 2 endpoints, one for editing a user profile and an admin endpoint for editing a user profile and role. Update the ac to state that’s what you’re doing

**Comment by Matt-Beldon-CDS** [comment]
> Ok, create 2 endpoints, one for editing a user profile and an admin endpoint for editing a user profile and role. Update the ac to state that’s what you’re doing

does it have to be profile and role or can it just be role? I'd like to avoid this multipart content as much as possible.

**Pull request merged**
